FROM node:20-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy all files
COPY . .

RUN npx prisma generate


# Expose port
EXPOSE 3000

# Start in dev mode (hot reload)
CMD ["npm", "run", "start:dev"]
