name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      # Run Prettier check
      - name: Check code format
        run: npm run format -- --check

      # Run ESLint check
      - name: Lint code
        run: npm run lint

      # Run tests
      - name: Run tests
        run: npm test

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-app-ci .
